spring.application.name=DairyMartApp

# Local
spring.datasource.url=jdbc:postgresql://localhost:5432/dairymart
spring.datasource.username=admin
spring.datasource.password=admin

#AWS
#spring.datasource.url=jdbc:postgresql://dairymartdatabase.cri6uuws02ew.ap-south-1.rds.amazonaws.com:5432/dairymart
#spring.datasource.username=postgres
#spring.datasource.password=MBMSwLsA81ytzFj6iGoK


spring.datasource.driverClassName=org.postgresql.Driver

spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.hibernate.naming.physical-strategy=org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
spring.jpa.hibernate.naming.implicit-strategy=org.hibernate.boot.model.naming.ImplicitNamingStrategyLegacyJpaImpl

logging.file.name=C://Users//akgbi//Documents//application.log

#spring.security.oauth2.client.registration.google.clientId=137271034236-1v7kd3cic2d2aejcphkihe8efrfdjae8.apps.googleusercontent.com
#spring.security.oauth2.client.registration.google.clientSecret=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
#spring.security.oauth2.client.registration.google.scope=read,write,openid
#spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
#spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8080/dairymart/login/oauth2/code/custom

#spring.thymeleaf.cache=false

#security.basic.enabled=true

# Google Sheets Configuration
google.sheets.spreadsheet.id=1LQVsNQyAO46JB-4YWMngHKLsWX6f5wNe8QzWH6vKTGg
google.sheets.sheet.name=Dairy Mart dump
google.sheets.credentials.path=classpath:credentials.json

# Enable Spring's scheduling capabilities
spring.task.scheduling.enabled=true